### ISSUE TITLE
Add support DataNucleus

### ISSUE THREAD

**Issue by divinespear** [divinespear/jpa-schema-gradle-plugin#19]
Before work #14, DataNucleus not supported by spring-data-jpa, so some class to be created.

**Comment by divinespear** [comment]
maybe later...

**Comment by divinespear** [comment]
WTF! DataNucleus does not support generate DDL without connection!

**Comment by andyjefferson** [comment]
WTF?, DataNucleus uses a connection to get the database capabilities, which seems like a perfectly reasonable thing to do, because otherwise the persistence provider is then hardcoding things that may or may not remain the same for all future versions of that database. 
Oh, and the JPA spec requires a JDBC connection definition for a JPA provider to generate DDL (as per JPA 2.1 semantics).
